version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: main
    open-pull-requests-limit: 3
    schedule:
      interval: weekly
    labels:
      - maintenance
    commit-message:
      prefix: "[DEPENDABOT]"

  - package-ecosystem: maven
    directory: "/"
    target-branch: main
    open-pull-requests-limit: 50
    schedule:
      interval: daily
      time: "00:00"
      timezone: "Asia/Shanghai"
