server.port: 9999


spring.application.name: authorization

jwt.publicKey: classpath:app.pub
# DO NOT Store private key in the Git Repository
# This is a sample application, and I added it only for demonstration purposes
jwt.privateKey: classpath:app.key

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka}:8761/eureka
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
management.endpoint.health.probes.enabled: true

logging:
  level:
    org.springframework.security: TRACE
