server.port: 8083
server.shutdown: graceful
# make sure requests the proxy uri instead of the server one
server.forward-headers-strategy: framework

spring.application.name: bookstore-product
spring.mvc.problemdetails.enabled: true

management.endpoints.web.exposure.include: "*"
management.metrics.tags.application: "${spring.application.name}"

spring.datasource.url: jdbc:postgresql://localhost:25432/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres
spring.jpa.open-in-view: false

# Enable /actuator/logfile endpoint for all apps
logging.file.path: logs/${spring.application.name}
---
spring.config.activate.on-profile: docker

spring.datasource.url: jdbc:postgresql://postgres-product:5432/postgres

# docker容器中用户无法创建路径，故使用/tmp/logs
logging.file.path: /tmp/logs/${spring.application.name}