# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring.application.name: authorization

spring.config.import: optional:configserver:http://localhost:8888/

---
spring.config.activate.on-profile: docker

spring.config.import: configserver:http://config-server:8888
