secrets:

  config-server-secrets:
    ENCRYPT_KEY: my-very-secure-encrypt-key
    SPRING_SECURITY_USER_NAME: dev-usr
    SPRING_SECURITY_USER_PASSWORD: dev-pwd

  config-product-credentials:
    CONFIG_SERVER_USR: dev-usr
    CONFIG_SERVER_PWD: dev-pwd

mysql:
  env:
    MYSQL_ROOT_PASSWORD: rootpwd
    MYSQL_DATABASE: review-db
    MYSQL_USER: user
    MYSQL_PASSWORD: pwd

config-server:
  envFromSecretRefs:
    - config-server-secrets

gateway:
  envFromSecretRefs:
    - config-product-credentials

authorization:
  envFromSecretRefs:
    - config-product-credentials

product:
  envFromSecretRefs:
    - config-product-credentials

recommendation:
  envFromSecretRefs:
    - config-product-credentials

review:
  envFromSecretRefs:
    - config-product-credentials

product-composite:
  envFromSecretRefs:
    - config-product-credentials

