services:
  customer-service:
    image: chensoul/sb3m-customer-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker

  notification-service:
    image: chensoul/sb3m-notification-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker

  order-service:
    image: chensoul/sb3m-order-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker

  payment-service:
    image: chensoul/sb3m-payment-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker

  product-service:
    image: chensoul/sb3m-product-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
