server:
  port: 8040

spring.application.name: order-service

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.chensoul.ecommerce.order.OrderConfirmation

application:
  config:
    customer-url: http://localhost:8020
    payment-url: http://localhost:8050
    product-url: http://localhost:8060
    notification-url: http://localhost:8030

---
spring.config.activate.on-profile: docker

server.port: 8080

spring.datasource.url: jdbc:postgresql://postgres:5432/ecommerce
spring.kafka.consumer.bootstrap-servers: kafka:9092

application:
  config:
    customer-url: http://customer-service:8080
    payment-url: http://payment-service:8080
    product-url: http://product-service:8080
    notification-url: http://notification-service:8080