services:
  customer-service:
    image: chensoul/customer-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy

  notification-service:
    image: chensoul/notification-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started

  notification-service-p1:
    image: chensoul/notification-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started

  order-service:
    image: chensoul/order-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

  order-service-p1:
    image: chensoul/order-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

  payment-service:
    image: chensoul/payment-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

  payment-service-p1:
    image: chensoul/payment-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

  product-service:
    image: chensoul/product-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,kafka
    depends_on:
      postgres:
        condition: service_started


postgres:
  extends:
    file: compose.yml
    service: postgres

  mongodb:
    extends:
      file: compose.yml
      service: mongodb

  maildev:
    extends:
      file: compose.yml
      service: maildev

  zookeeper:
    extends:
      file: compose.yml
      service: zookeeper

  kafka:
    extends:
      file: compose.yml
      service: kafka

  rabbitmq:
    extends:
      file: compose.yml
      service: rabbitmq

volumes:
  postgres:
  mongo:
  rabbitmq:
