services:
  customer-service:
    image: chensoul/sbme-customer-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker

  notification-service:
    image: chensoul/sbme-notification-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0

  notification-service-p1:
    image: chensoul/sbme-notification-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1

  order-service:
    image: chensoul/sbme-order-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0

  order-service-p1:
    image: chensoul/sbme-order-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1

  payment-service:
    image: chensoul/sbme-payment-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0

  payment-service-p1:
    image: chensoul/sbme-payment-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1

  product-service:
    image: chensoul/sbme-product-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
