server.port: 8083
server.shutdown: graceful
server.forward-headers-strategy: framework

spring.application.name: bookstore-product

management.endpoints.web.exposure.include: "*"
management.metrics.tags.application: "${spring.application.name}"
management.tracing.sampling.probability: 1.0
management.zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

spring.datasource.url: jdbc:postgresql://localhost:25432/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres
spring.jpa.open-in-view: false

---
spring.config.activate.on-profile: docker

spring.datasource.url: jdbc:postgresql://postgres-product:5432/postgres

management.zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans


