server:
  shutdown: graceful
  wait-for-shutdown: 10s

# Logging
# spring-admin-server 查看日志 https://docs.spring-boot-admin.com/current/client.html
logging.file.name: logs/${spring.application.name}/all.log
logging.level.org.springframework: INFO

# Metrics
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
management.tracing.sampling.probability: 1.0

loki.url: http://localhost:3100/loki/api/v1/push
