server:
  # make sure requests the proxy uri instead of the server one
  forward-headers-strategy: framework
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024

spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    problemdetails:
      enabled: true
  jmx:
    enabled: false
  task:
    execution:
      thread-name-prefix: task-
      pool:
        core-size: 4
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: scheduling-
      pool:
        size: 4


# Enable /actuator/logfile endpoint for all apps
logging.file.path: logs/${spring.application.name}

# Metrics
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
management.tracing.sampling.probability: 1.0

management.zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans
