server.port: 8020

spring.application.name: customer-service

spring.main.allow-bean-definition-overriding: true

spring:
  data:
    mongodb:
      username: user
      password: pass
      host: localhost
      port: 27017
      database: ecommerce
      authentication-database: admin

---
spring.config.activate.on-profile: docker

server.port: 8080

# docker容器中用户无法创建路径，故使用/tmp/logs
logging.file.path: /tmp/logs/${spring.application.name}

spring.data.mongodb.host: mongodb

eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
