services:
  bookstore-notification:
    image: chensoul/bookstore-notification
    container_name: bookstore-notification
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  bookstore-order:
    image: chensoul/bookstore-order
    container_name: bookstore-order
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8082:8082"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  bookstore-product:
    image: chensoul/bookstore-product
    container_name: bookstore-product
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8083:8083"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  bookstore-webapp:
    image: chensoul/bookstore-webapp
    container_name: bookstore-webapp
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
