spring.application.name: product-service
server.port: 8083
server.shutdown: graceful
server.forward-headers-strategy: framework

management.info.git.mode: full
management.endpoints.web.exposure.include: "*"
management.metrics.tags.application: "${spring.application.name}"
management.tracing.enabled: false
management.tracing.sampling.probability: 1.0

spring.datasource.url: jdbc:postgresql://localhost:25432/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres
spring.jpa.open-in-view: false


---
spring.config.activate.on-profile: docker

spring.datasource.url: jdbc:postgresql://postgres-product:5432/postgres

