# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server.port: 8040

spring.application.name: order-service

spring.main.allow-bean-definition-overriding: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings:
    notification-out-0:
      destination: notification
      producer:
        required-groups: auditGroup

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

application:
  config:
    customer-url: http://localhost:8020/api/v1/customers
    payment-url: http://localhost:8050/api/v1/payments
    product-url: http://localhost:8060/api/v1/products

---
spring.config.activate.on-profile: docker

server.port: 8080

# docker容器中用户无法创建路径，故使用/tmp/logs
logging.file.path: /tmp/logs/${spring.application.name}

spring.datasource.url: jdbc:postgresql://postgres:5432/ecommerce

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka

application:
  config:
    customer-url: http://customer-service:8080/api/v1/customers
    payment-url: http://payment-service:8080/api/v1/payments
    product-url: http://product-service:8080/api/v1/products

---
spring.config.activate.on-profile: streaming_partitioned

spring.cloud.stream.bindings.notification-out-0.producer:
  partition-key-expression: headers['partitionKey']
  partition-count: 2

---
spring.config.activate.on-profile: kafka

management.health.rabbit.enabled: false
spring.cloud.stream.defaultBinder: kafka
spring.kafka.bootstrap-servers: kafka:9092
spring.cloud.stream.kafka.binder.replication-factor: 1
