name: ecommerce

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
      interval: 5s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://user:pass@localhost:27017/?authSource=admin --quiet
      interval: 5s
      timeout: 2s
      retries: 10

  maildev:
    image: maildev/maildev
    environment:
      TZ: Asia/Shanghai
      MAILDEV_OUTGOING_USER: user
      MAILDEV_OUTGOING_PASS: pass
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  postgres:
  mongo:
