services:
  customer-service:
    image: chensoul/sbme-customer-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker

  notification-service:
    image: chensoul/sbme-notification-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker

  order-service:
    image: chensoul/sbme-order-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker

  payment-service:
    image: chensoul/sbme-payment-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker

  product-service:
    image: chensoul/sbme-product-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker

  eureka-server:
    image: chensoul/sbme-eureka-server
    container_name: eureka-server #单节点，需要指定容器名称
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://eureka-server:8761" ]
      interval: 5s
      timeout: 3s
      retries: 10

  gateway:
    image: chensoul/sbme-gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy

  config-server:
    image: chensoul/sbme-config-server
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=native,docker
    volumes:
      - ./spring-cloud/config-server/src/main/resources/config-repo:/config-repo
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://config-server:8888" ]
      interval: 5s
      timeout: 5s
      retries: 10
