apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: product
spec:
  hosts:
    - client
  http:
    - route:
        - destination:
            host: client
      fault:
        delay:
          fixedDelay: 3s
          percent: 100
