services:
  customer-service:
    image: chensoul/sb3m-customer-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
    labels:
      logging: "promtail"

  bookstore-notification:
    image: chensoul/sb3m-bookstore-notification
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
    labels:
      logging: "promtail"

  bookstore-order:
    image: chensoul/sb3m-bookstore-order
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
    labels:
      logging: "promtail"

  payment-service:
    image: chensoul/sb3m-payment-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
    labels:
      logging: "promtail"

  bookstore-product:
    image: chensoul/sb3m-bookstore-product
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
    labels:
      logging: "promtail"

  eureka-server:
    image: chensoul/sb3m-eureka-server
    container_name: eureka-server #单节点，需要指定容器名称
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://eureka-server:8761" ]
      interval: 5s
      timeout: 3s
      retries: 10

  gateway:
    image: chensoul/sb3m-gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
    labels:
      logging: "promtail"

  config-server:
    image: chensoul/sb3m-config-server
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=native,docker
    volumes:
      - ./spring-cloud/config-server/src/main/resources/config-repo:/config-repo
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://config-server:8888" ]
      interval: 5s
      timeout: 5s
      retries: 10

  authorization:
    image: chensoul/sb3m-authorization
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      eureka-server:
        condition: service_healthy
    labels:
      logging: "promtail"

  admin-server:
    image: chensoul/sb3m-admin-server
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      eureka-server:
        condition: service_healthy
    labels:
      logging: "promtail"