server.port: 8050

spring.application.name: payment-service

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.chensoul.ecommerce.payment.PaymentConfirmation

application:
  config:
    notification-url: http://localhost:8030/api/v1/notifications

---
spring.config.activate.on-profile: docker

server.port: 8080

spring.datasource.url: jdbc:postgresql://postgres:5432/ecommerce
spring.kafka.consumer.bootstrap-servers: kafka:9092


application:
  config:
    notification-url: http://notification-service:8080/api/v1/notifications
