spring.application.name: order-service
server.port: 8082
server.shutdown: graceful
server.forward-headers-strategy: framework
spring.mvc.problemdetails.enabled: true

order.product-service-url: http://localhost:8083
order.order-event-exchange: order-exchange
order.new-order-queue: new-order
order.delivered-order-queue: delivered-order
order.cancelled-order-queue: cancelled-order
order.error-order-queue: error-order
order.publish-order-events-job-cron: "*/5 * * * * *"
order.new-order-job-cron: "*/10 * * * * *"

management.endpoints.web.exposure.include: "*"
management.metrics.tags.application: "${spring.application.name}"

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:9000

spring.datasource.url: jdbc:postgresql://localhost:15432/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres
spring.jpa.open-in-view: false
spring.jpa.show-sql: true

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderCreatedEvent:com.chensoul.bookstore.order.OrderCreatedEvent,orderDeliveredEvent:com.chensoul.bookstore.order.OrderDeliveredEvent,orderCancelledEvent:com.chensoul.bookstore.order.OrderCancelledEvent,orderErrorEvent:com.chensoul.bookstore.order.OrderErrorEvent

resilience4j.retry.backends.product-service.max-attempts: 2
resilience4j.retry.backends.product-service.wait-duration: 1s
resilience4j.circuitbreaker.backends.product-service.sliding-window-type: COUNT_BASED
resilience4j.circuitbreaker.backends.product-service.sliding-window-size: 6
resilience4j.circuitbreaker.backends.product-service.minimum-number-of-calls: 4
resilience4j.circuitbreaker.backends.product-service.wait-duration-in-open-state: 20s
resilience4j.circuitbreaker.backends.product-service.permitted-number-of-calls-in-half-open-state: 2
resilience4j.circuitbreaker.backends.product-service.failure-rate-threshold: 50


---
spring.config.activate.on-profile: docker

order.product-service-url: http://product-service:8083

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://spring-authorization-server:9000

spring.datasource.url: jdbc:postgresql://postgres-order:5432/postgres

spring.data.mongodb.host: mongodb
