server.port: 8083
server.shutdown: graceful
# make sure requests the proxy uri instead of the server one
server.forward-headers-strategy: framework

spring.application.name: bookstore-product
spring.mvc.problemdetails.enabled: true

management.endpoints.web.exposure.include: "*"
management.metrics.tags.application: "${spring.application.name}"

spring.datasource.url: jdbc:postgresql://localhost:25432/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres
spring.jpa.open-in-view: false

# Enable /actuator/logfile endpoint for all apps
logging.file.path: logs/${spring.application.name}
---
spring.config.activate.on-profile: docker

spring.datasource.url: jdbc:postgresql://postgres-product:5432/postgres

eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/


