# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server.port: 8888

spring.application.name: config-server

spring.profiles.active: native

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/chensoul/spring-boot-microservices-ecommerce-config
#          default-label: main


# 需要启用 native profile。在 Idea 中， ${PWD} 可能指向的是项目跟路径，也可以通过 $MODULE_WORKING_DIR$ 设置为模块工作路径
spring.cloud.config.server.native.searchLocations: file:${PWD}/config-repo,classpath:/config-repo



---
spring.config.activate.on-profile: docker

spring.cloud.config.server.native.searchLocations: file:/config-repo
