server.port: 8020

spring.application.name: customer-service

spring:
  data:
    mongodb:
      username: user
      password: pass
      host: localhost
      port: 27017
      database: ecommerce
      authentication-database: admin


---
spring.config.activate.on-profile: docker

server.port: 8080

spring.data.mongodb.host: mongodb
